// actions types

export const LOAD_HOME_CONTENT_DATA = 'LOAD_HOME_CONTENT_DATA';
export const LOAD_HOME_BANNER_DATA = 'LOAD_HOME_BANNER_DATA';
export const LOAD_HOME_FIELD_QUICK_LINKS_DATA =
  'LOAD_HOME_FIELD_QUICK_LINKS_DATA';
export const LOAD_HOME_OUR_CUSTOMER_PROMISES_DATA =
  'LOAD_HOME_OUR_CUSTOMER_PROMISES_DATA';
export const LOAD_HOME_TRUSTED_PROVIDER_DATA =
  'LOAD_HOME_TRUSTED_PROVIDER_DATA';
export const LOAD_NEWS_ARTICLES_CONTENT_DATA =
  'LOAD_NEWS_ARTICLES_CONTENT_DATA';
export const LOAD_NEWS_ARTICLES_BANNER_DATA = 'LOAD_NEWS_ARTICLES_BANNER_DATA';
export const LOAD_NEWS_CATEGORIES_DATA = 'LOAD_NEWS_CATEGORIES_DATA';
export const LOAD_NEWS_ARTICLES_LIST_DATA = 'LOAD_NEWS_ARTICLES_LIST_DATA';

export const LOAD_DOCUMENT_LIBRARY_DATA = 'LOAD_DOCUMENT_LIBRARY_DATA';
export const LOAD_BRIDGING_FINANCE_CONTENT_DATA =
  'LOAD_BRIDGING_FINANCE_CONTENT_DATA';
export const LOAD_MEET_THE_TEAM_CONTENT_DATA =
  'LOAD_MEET_THE_TEAM_CONTENT_DATA';
export const LOAD_PERSONAL_SAVINGS_ONLINE_ISA_CONTENT_DATA =
  'LOAD_PERSONAL_SAVINGS_ONLINE_ISA_CONTENT_DATA';

export const LOAD_PROPERTY_FINANCE_MEET_TEAM_DATA =
  'LOAD_PROPERTY_FINANCE_MEET_TEAM_DATA';
export const LOAD_PROPERTY_FINANCE_MEET_TEAM_BANNER_DATA =
  'LOAD_PROPERTY_FINANCE_MEET_TEAM_BANNER_DATA';
export const LOAD_PROPERTY_FINANCE_MEET_TEAM_TEAMS_DATA =
  'LOAD_PROPERTY_FINANCE_MEET_TEAM_TEAMS_DATA';
export const LOAD_PROPERTY_FINANCE_MEET_TEAM_CUSTOMER_FEEDBACK =
  'LOAD_PROPERTY_FINANCE_MEET_TEAM_CUSTOMER_FEEDBACK';

export const LOAD_CUSTOMER_SUPPORT_CONTACT_US_CONTENT_DATA =
  'LOAD_CUSTOMER_SUPPORT_CONTACT_US_CONTENT_DATA';
export const LOAD_CONTACT_FORM_DATA = 'LOAD_CONTACT_FORM_DATA';
export const LOAD_BUSINESS_RELATIONSHIP_MANAGER_CONTENT_DATA =
  'LOAD_BUSINESS_RELATIONSHIP_MANAGER_CONTENT_DATA';
export const LOAD_ARTICLE_DETAIL_CONTENT_DATA =
  'LOAD_ARTICLE_DETAIL_CONTENT_DATA';
export const LOAD_FAQ_INDIVIDUAL_CONTENT_DATA =
  'LOAD_FAQ_INDIVIDUAL_CONTENT_DATA';

export const LOAD_BUSINESS_CURRENT_ACCOUNT_DATA =
  'LOAD_BUSINESS_CURRENT_ACCOUNT_DATA';
export const LOAD_BUSINESS_BANNER_DATA = 'LOAD_BUSINESS_BANNER_DATA';
export const LOAD_BUSINESS_HIGHLIGHTED_DATA = 'LOAD_BUSINESS_HIGHLIGHTED_DATA';
export const LOAD_BUSINESS_HIGHLIGHTED_CARDS =
  'LOAD_BUSINESS_HIGHLIGHTED_CARDS';
export const LOAD_BUSINESS_CA_COMPARE_ACCOUNTS_DATA =
  'LOAD_BUSINESS_CA_COMPARE_ACCOUNTS_DATA';
export const LOAD_BUSINESS_CA_BENEFITS_DATA = 'LOAD_BUSINESS_CA_BENEFITS_DATA';
export const LOAD_BUSINESS_CA_TRUSTED_PROVIDER_DATA =
  'LOAD_BUSINESS_CA_TRUSTED_PROVIDER_DATA';
export const LOAD_PERSONAL_CURRENT_ACCOUNT_DATA =
  'LOAD_PERSONAL_CURRENT_ACCOUNT_DATA';
export const LOAD_PERSONAL_BANNER_DATA = 'LOAD_PERSONAL_BANNER_DATA';
export const LOAD_PERSONAL_HIGHLIGHTED_DATA = 'LOAD_PERSONAL_HIGHLIGHTED_DATA';
export const LOAD_PERSONAL_HIGHLIGHTED_CARDS =
  'LOAD_PERSONAL_HIGHLIGHTED_CARDS';
export const LOAD_PERSONAL_CA_COMPARE_ACCOUNTS_DATA =
  'LOAD_PERSONAL_CA_COMPARE_ACCOUNTS_DATA';
export const LOAD_PERSONAL_CA_BENEFITS_DATA = 'LOAD_PERSONAL_CA_BENEFITS_DATA';
export const LOAD_PERSONAL_CA_TRUSTED_PROVIDER_DATA =
  'LOAD_PERSONAL_CA_TRUSTED_PROVIDER_DATA';
export const LOAD_PERSONAL_SAVING_ACCOUNT_DATA =
  'LOAD_PERSONAL_SAVING_ACCOUNT_DATA';
export const LOAD_PERSONAL_SAVING_BANNER_DATA =
  'LOAD_PERSONAL_SAVING_BANNER_DATA';
export const LOAD_PERSONAL_SA_COMPARE_ACCOUNTS =
  'LOAD_PERSONAL_SA_COMPARE_ACCOUNTS';
export const LOAD_PERSONAL_SA_ADD_AWARENESS = 'LOAD_PERSONAL_SA_ADD_AWARENESS';

export const LOAD_CURRENT_ACCOUNTS_CONTENT_DATA =
  'LOAD_CURRENT_ACCOUNTS_CONTENT_DATA';
export const LOAD_CURRENT_ACCOUNTS_BANNER_DATA =
  'LOAD_CURRENT_ACCOUNTS_BANNER_DATA';
export const LOAD_CURRENT_ACCOUNTS_HEADER_LINKS_DATA =
  'LOAD_CURRENT_ACCOUNTS_HEADER_LINKS_DATA';
export const LOAD_CURRENT_ACCOUNTS_CUSTOMER_INTEREST_LINKS_DATA =
  'LOAD_CURRENT_ACCOUNTS_CUSTOMER_INTEREST_LINKS_DATA';
export const LOAD_CURRENT_ACCOUNTS_FIELD_COMPONENTS_DATA =
  'LOAD_CURRENT_ACCOUNTS_FIELD_COMPONENTS_DATA';
export const LOAD_CURRENT_ACCOUNTS_FAQS_DATA =
  'LOAD_CURRENT_ACCOUNTS_FAQS_DATA';
export const LOAD_CURRENT_ACCOUNTS_CARDS_WITH_LINK_TEXT_DATA =
  'LOAD_CURRENT_ACCOUNTS_CARDS_WITH_LINK_TEXT_DATA';

export const LOAD_ABOUT_US_CONTENT_DATA = 'LOAD_ABOUT_US_CONTENT_DATA';
export const LOAD_ABOUT_ODYSSEY_BANK_CONTENT_DATA = 'LOAD_ABOUT_ODYSSEY_BANK_CONTENT_DATA';
export const LOAD_ABOUT_US_BANNER_DATA = 'LOAD_ABOUT_US_BANNER_DATA';
export const LOAD_ABOUT_US_FIELD_COMPONENTS_DATA =
  'LOAD_ABOUT_US_FIELD_COMPONENTS_DATA';
export const LOAD_ABOUT_US_FAQS_DATA = 'LOAD_ABOUT_US_FAQS_DATA';
export const LOAD_ABOUT_US_ETHICS_VALUES_CONTENT_DATA = 'LOAD_ABOUT_US_ETHICS_VALUES_CONTENT_DATA';

export const LOAD_ERROR_404_CONTENT_DATA = 'LOAD_ERROR_404_CONTENT_DATA';
export const LOAD_MORTGAGE_CALCULATOR_CONTENT_DATA =
  'LOAD_MORTGAGE_CALCULATOR_CONTENT_DATA';

export const LOAD_CUSTOMER_SUPPORT_FAQS_CONTENT_DATA =
  'LOAD_CUSTOMER_SUPPORT_FAQS_CONTENT_DATA';
export const LOAD_PRIVATE_BANKING_CONTENT_DATA =
  'LOAD_PRIVATE_BANKING_CONTENT_DATA';
export const LOAD_PRIVATE_BANKING_BECOME_A_CLIENT_DATA =
  'LOAD_PRIVATE_BANKING_BECOME_A_CLIENT_DATA';
export const LOAD_PRIVATE_BANKING_THANKS_NOTE_DATA =
  'LOAD_PRIVATE_BANKING_THANKS_NOTE_DATA';
export const LOAD_PRIVATE_BANKING_BORROWING_CONTENT_DATA =
  'LOAD_PRIVATE_BANKING_BORROWING_CONTENT_DATA';

export const LOAD_IMPORTANT_INFORMATION_CONTENT_DATA =
  'LOAD_IMPORTANT_INFORMATION_CONTENT_DATA';
export const LOAD_BUSINESS_IDENTIFICATION_REQUIREMENTS_CONTENT_DATA =
  'LOAD_BUSINESS_IDENTIFICATION_REQUIREMENTS_CONTENT_DATA';
export const LOAD_PERSONAL_LIFE_EVENTS_CONTENT_DATA =
  'LOAD_PERSONAL_LIFE_EVENTS_CONTENT_DATA';
export const LOAD_ACCESSIBILITY_CONTENT_DATA =
  'LOAD_ACCESSIBILITY_CONTENT_DATA';
export const LOAD_PRIVATE_BANKING_HOW_TO_APPLY_CONTENT_DATA =
  'LOAD_PRIVATE_BANKING_HOW_TO_APPLY_CONTENT_DATA';
export const LOAD_PRIVATE_BANKING_INTERMEDIARIES_CONTENT_DATA =
  'LOAD_PRIVATE_BANKING_INTERMEDIARIES_CONTENT_DATA';
export const LOAD_FEE_AND_RATES_DATA = 'LOAD_FEE_AND_RATES_DATA';
export const LOAD_PERSONAL_CURRENT_ACCOUNT_PREMIUM_EUROS_DATA =
  'LOAD_PERSONAL_CURRENT_ACCOUNT_PREMIUM_EUROS_DATA';

export const LOAD_SECURITY_CONTENT_DATA = 'LOAD_SECURITY_CONTENT_DATA';
export const LOAD_SECURITY_CATEGORIES_DATA = 'LOAD_SECURITY_CATEGORIES_DATA';

export const LOAD_LOAN_COMPLETION_DATA = 'LOAD_LOAN_COMPLETION_DATA';
export const LOAD_LOAN_COMPLETION_BANNER = 'LOAD_LOAN_COMPLETION_BANNER'; 
export const LOAD_DEAL_SHEET_DATA='LOAD_DEAL_SHEET_DATA'
export const LOAD_DEAL_SHEET_BANNER = 'LOAD_DEAL_SHEET_BANNER';
export const LOAD_DEAL_SHEET_CONTENT = 'LOAD_DEAL_SHEET_CONTENT';

export const LOAD_HEADER_MENU_DATA = 'LOAD_HEADER_MENU_DATA';
export const LOAD_FOOTER_DATA = 'LOAD_FOOTER_DATA';

export const LOAD_DRUPAL_PAGE_TEMPLATE_DATA = 'LOAD_DRUPAL_PAGE_TEMPLATE_DATA';
